name: DevOps Mini Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t github-actions-demo .

      - name: Copy Project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Dockerfile,index.html"
          target: "/home/ubuntu/github-action-project1"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/github-action-project1

            docker stop github-actions-demo-container || true
            docker rm github-actions-demo-container || true

            docker build -t github-actions-demo .

            docker run -d \
              --name github-actions-demo-container \
              -p 80:80 \
              github-actions-demo